name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

env:
  SAM_CLI_TELEMETRY: 0

jobs:
  build-and-deploy-dev:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    environment: development
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Setup SAM CLI
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GitHubActions
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install dependencies
        run: |
          npm ci
          npm install -g esbuild

      - name: Build SAM application
        run: sam build

      - name: Deploy to Development
        run: |
          sam deploy \
            --stack-name oauth-service \
            --s3-prefix oauth-service \
            --region ${{ secrets.AWS_REGION }} \
            --capabilities CAPABILITY_IAM \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            --resolve-s3 \
            --parameter-overrides \
              Environment=dev \
              DomainName=${{ secrets.DOMAIN_NAME }} \
              CertificateArn=${{ secrets.CERTIFICATE_ARN }}
